id: A42EEE127
base_file: f434C.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:15:26.442815
  last_modified_at: 2022-05-31 05:15:26.442822
