id: A42EEE127
base_file: fEDA8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:15:26.445081
  last_modified_at: 2022-05-31 05:15:26.445086
